/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubesrevisi;

import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.ERROR;
import static java.awt.image.ImageObserver.WIDTH;
import java.beans.PropertyVetoException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.Timer;
import java.util.TimerTask;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        tampilkanText();
        tapmilkanWaktu();
        tampilkanTanggal();
        notifikasiTugas();
        Jadwal();
        tugas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDahsboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        ttbb = new javax.swing.JLabel();
        waktu = new javax.swing.JLabel();
        username = new javax.swing.JLabel();
        sekolah = new javax.swing.JLabel();
        greeting = new javax.swing.JLabel();
        panelTampil = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJadwal = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tugas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Dashboard");

        jButton1.setText("Jadwal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Tugas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        ttbb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ttbb.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ttbb.setText("tanggal");

        waktu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        waktu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        waktu.setText("jam");
        waktu.setAutoscrolls(true);

        username.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        username.setText("username");

        sekolah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sekolah.setText("sekolah");
        sekolah.setPreferredSize(new java.awt.Dimension(241, 133));

        greeting.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        greeting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        greeting.setText("nama");

        panelTampil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        javax.swing.GroupLayout panelTampilLayout = new javax.swing.GroupLayout(panelTampil);
        panelTampil.setLayout(panelTampilLayout);
        panelTampilLayout.setHorizontalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 846, Short.MAX_VALUE)
        );
        panelTampilLayout.setVerticalGroup(
            panelTampilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        listJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Jadwal", "Hari"
            }
        ));
        jScrollPane1.setViewportView(listJadwal);

        tugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Tugas", "Tenggat"
            }
        ));
        jScrollPane2.setViewportView(tugas);

        jButton4.setText("Perbarui");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelDahsboardLayout = new javax.swing.GroupLayout(panelDahsboard);
        panelDahsboard.setLayout(panelDahsboardLayout);
        panelDahsboardLayout.setHorizontalGroup(
            panelDahsboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDahsboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDahsboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sekolah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(greeting, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDahsboardLayout.createSequentialGroup()
                        .addGroup(panelDahsboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(waktu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ttbb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(12, 12, 12))
                    .addComponent(username, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTampil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelDahsboardLayout.setVerticalGroup(
            panelDahsboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDahsboardLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sekolah, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(ttbb, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDahsboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelTampil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelDahsboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelDahsboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jadwal HalJadwal = new jadwal();
        try {
            HalJadwal.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelTampil.add(HalJadwal);
        HalJadwal.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tugas HalTugas = new tugas();
        try {
            HalTugas.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
        panelTampil.add(HalTugas);
        HalTugas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        tugas();
        Jadwal();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tampilkanText(){
        try {
//          1.  Query
            String query = "SELECT * FROM tb_user";
            
//          2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();
            
//          3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
//          4.  Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            while (r.next()) {
                String data = r.getString(2); String tempat = r.getString(3);
                String user = r.getString(4);
                greeting.setText("Nama : " + data);
                sekolah.setText("Sekolah : " + tempat);
                username.setText("Username : " +user);
            }
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan saat menampilkan data ke lable: " + e.getMessage());
        }
    }
    
    public void notifikasi(){
        try {
//          1.  Query
            String query = "SELECT tenggat FROM tb_tugas ";
            
//          2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();
            
//          3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
//          4.  Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
            while (r.next()) {
                String data = r.getString(2); String tempat = r.getString(3);
                String user = r.getString(4);
            }
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan saat menampilkan data ke lable: " + e.getMessage());
        }
   }
    
    public void tapmilkanWaktu(){
        Timer timer = new Timer(1000, new ActionListener(){
        public void actionPerformed(ActionEvent e){
         Date now = new Date();
                SimpleDateFormat formatter = new SimpleDateFormat("HH:mm:ss");
                String waktuFormatted = formatter.format(now);

                // Menampilkan waktu pada JLabel
                waktu.setText(waktuFormatted);
     }
        
    });
        timer.start();
    }
    
    public void tampilkanTanggal(){
        Timer timer = new Timer(1000, new ActionListener(){
        public void actionPerformed(ActionEvent e){
         Date now = new Date();
                SimpleDateFormat formatter = new SimpleDateFormat("dd MMMM yyyy");
                String tanggal = formatter.format(now);
                // Menampilkan waktu pada JLabel
                ttbb.setText(tanggal);
     }
        
    });
        timer.start();
    }
    
  public void notifikasiTugas(){
      
                var dateList = new ArrayList<Date>();
                var List = new ArrayList<String>();
                
                  try {

       //       1.  Query
                 String query = "SELECT tenggat FROM tb_tugas";

       //       2.  Fungsi koneksi
                java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();

       //       3.  Kirim Paramter fungsi Java ke SQL
                java.sql.Statement s = Vconn.createStatement();

       //       4.  Eksekusi Query
                java.sql.ResultSet r = s.executeQuery(query);

                 while (r.next()){
                 java.sql.Date sqlDate = r.getDate("tenggat");
                 Date utilDate = new Date(sqlDate.getTime());
                 dateList.add(utilDate);
                 
            }
               } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Gagal Ubah");
                 System.out.println("Terjadi kesalahan saat mengubah data: " + e.getMessage());
               }
                  
                  try{
       //          1.  Query
                 String query = "SELECT descTugas FROM tb_tugas";

       //       2.  Fungsi koneksi
                java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();

       //       3.  Kirim Paramter fungsi Java ke SQL
                java.sql.Statement s = Vconn.createStatement();

       //       4.  Eksekusi Query
                java.sql.ResultSet r = s.executeQuery(query);
                 
                 while (r.next()){
                 String tugas = r.getString("descTugas");
                 List.add(tugas);
                 }
                  }catch(Exception e){
                      JOptionPane.showMessageDialog(this, "Error : "+ e.getMessage());
                  }
                  
         Date currentTime = new Date();
         int list = 0;
        // Membandingkan setiap elemen dengan waktu tanggal real-time
        for (Date date : dateList) {
           
                ArrayList<String> tugas = List;
            if (date.before(currentTime)) {
                JOptionPane.showMessageDialog(panelTampil, "Tugas Berikut : " + tugas.get(list) + " telah lewat waktu.");
                //System.out.println("Tugas Berikut : " + tugas.get(list) + " telah lewat waktu.");
            } else if (date.after(currentTime)) {
                JOptionPane.showMessageDialog(panelTampil, "Tugas Berikut : " + tugas.get(list) +  " belum sampai waktu.");
                System.out.println("Tugas Berikut : " + tugas.get(list) +  " belum sampai waktu.");
            } else {
                JOptionPane.showMessageDialog(panelTampil, "Tugas Berikut : " + tugas.get(list) +  " adalah waktu saat ini.");
                System.out.println("Tugas Berikut : " + tugas.get(list) +  " adalah waktu saat ini.");
            }
            list = list + 1;
        }
  }
  
 public void Jadwal(){
     DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("Jadwal");
        tb1.addColumn("Hari");
       
        try {
//          1.  Query
            String query = "SELECT matkul, hari FROM tb_jadwal";
            
//          2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();
            
//          3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
//          4.  Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
//          5. Looping  
            while (r.next()) {
                tb1.addRow(new Object[]{
                    r.getString(1),r.getString(2)
                });
            }
            listJadwal.setModel(tb1);
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan saat menambahkan data ke tabel: " + e.getMessage());
        }
 }
 
 public void tugas(){
     DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("Tugas");
        tb1.addColumn("Tenggat");
       
        try {
           
//          1.  Query
            String query = "SELECT descTugas, tenggat FROM tb_tugas";
            
//          2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();
            
//          3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
//          4.  Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
//          5. Looping  
            while (r.next()) {
                tb1.addRow(new Object[]{
                    r.getString(1),r.getString(2)
                });
            }
            tugas.setModel(tb1);
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan saat menambahkan data ke tabel: " + e.getMessage());
        }
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel greeting;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable listJadwal;
    private javax.swing.JPanel panelDahsboard;
    private javax.swing.JPanel panelTampil;
    private javax.swing.JLabel sekolah;
    private javax.swing.JLabel ttbb;
    private javax.swing.JTable tugas;
    private javax.swing.JLabel username;
    private javax.swing.JLabel waktu;
    // End of variables declaration//GEN-END:variables
}
