/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tubesrevisi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import java.sql.Time;
import javax.swing.Timer;

/**
 *
 * @author DELL
 */
public class jadwal extends javax.swing.JInternalFrame {

    /**
     * Creates new form jadwal
     */
    public jadwal() {
        initComponents();
        tampilkanJadwal();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matkul = new javax.swing.JTextField();
        sks = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilJadwal = new javax.swing.JTable();
        hari = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        Date date = new Date();
        SpinnerDateModel sm =
        new SpinnerDateModel(date, null, null, Calendar.HOUR);
        jam = new javax.swing.JSpinner(sm);

        setClosable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Jadwal Mata Kuliah");

        jLabel2.setText("Nama Mata Kuliah");

        jLabel3.setText("Jumlah SKS");

        jLabel4.setText("Hari");

        jLabel5.setText("Jam");

        matkul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matkulMouseClicked(evt);
            }
        });
        matkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matkulActionPerformed(evt);
            }
        });

        sks.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sksActionPerformed(evt);
            }
        });

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tampilJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Mata Kuliah", "SKS", "Hari", "Jam"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tampilJadwal.getTableHeader().setReorderingAllowed(false);
        tampilJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilJadwalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampilJadwal);

        jScrollPane2.setViewportView(jScrollPane1);

        hari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Hari", "Senin", "Selasa", "Rabu", "Kamis", "Jumat" }));

        jLabel6.setText("ID");

        id.setEditable(false);
        id.setText("Tidak Di Isi");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        JSpinner.DateEditor de = new JSpinner.DateEditor(jam, "HH:mm:ss");
        jam.setEditor(de);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sks)
                                    .addComponent(id, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(matkul)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jam))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(matkul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(sks, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(hari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sksActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sksActionPerformed
        // TODO add your handling code here:
        sks.setText("");
        formatWaktu();
    }//GEN-LAST:event_sksActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(matkul.equals("") && sks.equals("") && hari.equals("Pilih Hari") && jam.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Lengkap Terlebih Dahulu");
        }else{
            String nmMatkul = matkul.getText();
        String jmlSks = sks.getText();
        String pilHari = (String) hari.getSelectedItem();
        Date wktuJam =  (Date) jam.getValue();
        
         Calendar calendar = Calendar.getInstance();
          calendar.setTime(wktuJam);
        int hours = calendar.get(Calendar.HOUR);
        int minutes = calendar.get(Calendar.MINUTE);
        int seconds = calendar.get(Calendar.SECOND);
        
        String hur = String.valueOf(hours);
        String menit = String.valueOf(minutes);
        String detik = String.valueOf(seconds);
        
         String hour = hur+":"+menit+":"+detik;
        
        //SimpleDateFormat sdf = new SimpleDateFormat("HH:mm:ss");
//         DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HHmmss");
//        LocalTime time = LocalTime.parse(wktuJam, formatter);
//        String timeString = time.format(formatter);
//        System.out.print(timeString);
            
        String sql = "INSERT INTO tb_jadwal (matkul, sks, hari, jam) VALUES (?, ?, ?, ?)";
            String value1 = nmMatkul;
            String value2 = jmlSks;
            String value3 = pilHari;
            String value4 = hour;
            
       try(Connection Vconn = (Connection)koneksiDB.configDB();
                PreparedStatement pstmt = Vconn.prepareStatement(sql)){
                
                pstmt.setString(1, value1);
                pstmt.setString(2, value2);
                pstmt.setString(3,value3);
                pstmt.setString(4, value4);
                pstmt.executeUpdate();
                
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan");
                matkul.setText("");
                sks.setText("");
                jam.setValue("");
                System.out.println("Data berhasil ditambahkan ke tabel.");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal Menambahkan");
                System.out.println("Terjadi kesalahan saat menambahkan data ke tabel: " + e.getMessage());
            }
               tampilkanJadwal();
        }
        
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if(matkul.equals("") && sks.equals("") && hari.equals("Pilih Hari") && jam.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Lengkap Terlebih Dahulu");
        }else{
            String ID = id.getText();
            String nmMatkul = matkul.getText();
            String jmlSks = sks.getText();
            String pilHari = (String) hari.getSelectedItem();
            Date wktuJam =  (Date) jam.getValue();
        
         Calendar calendar = Calendar.getInstance();
          calendar.setTime(wktuJam);
        int hours = calendar.get(Calendar.HOUR);
        int minutes = calendar.get(Calendar.MINUTE);
        int seconds = calendar.get(Calendar.SECOND);
        
        String hur = String.valueOf(hours);
        String menit = String.valueOf(minutes);
        String detik = String.valueOf(seconds);
        
        String hour = hur+":"+menit+":"+detik;

            try {

       //       1.  Query
                 String query = "UPDATE tb_jadwal SET matkul = '"+nmMatkul+"', sks = '"+jmlSks+"', hari = '"+pilHari+"', jam = '"+hour+"' WHERE id = '"+ID+"';";

       //       2.  Fungsi koneksi
                java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();

       //       3.  Kirim Paramter fungsi Java ke SQL
                java.sql.Statement s = Vconn.createStatement();

       //       4.  Eksekusi Query
                s.executeUpdate(query);

                JOptionPane.showMessageDialog(null, "Berhasil Ubah");
               } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Gagal Ubah");
                 System.out.println("Terjadi kesalahan saat mengubah data: " + e.getMessage());
               }
            tampilkanJadwal();
            
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void matkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matkulActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String input = id.getText();
        int option = JOptionPane.showConfirmDialog(null,  "Anda yakin Ingin Keluar Menghapus Jadwal?");
        if(option == 0){
            try {

   //       1.  Query
            String query = "DELETE FROM tb_jadwal WHERE id = "+ input +";";

   //       2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();

   //       3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();

   //       4.  Eksekusi Query
            s.executeUpdate(query);

           } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "gagal hapus");
             System.out.println("Terjadi kesalahan saat menghapus data: " + e.getMessage());
           }
            tampilkanJadwal();
        }else{
            JOptionPane.showMessageDialog(null, "Hapus Tidak Valid");
            JOptionPane.getRootFrame().dispose();
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tampilJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilJadwalMouseClicked
        // TODO add your handling code here:
        int baris = tampilJadwal.rowAtPoint(evt.getPoint());
        
        String ID = tampilJadwal.getValueAt(baris, 1).toString();
        id.setText(ID);
        
        String mk = tampilJadwal.getValueAt(baris, 2).toString();
        matkul.setText(mk);
        
        String sk = tampilJadwal.getValueAt(baris, 3).toString();
        sks.setText(sk);
        
        String hr = tampilJadwal.getValueAt(baris, 4).toString();
        hari.setSelectedItem(hr);
        
        String wkt = tampilJadwal.getValueAt(baris, 5).toString();
        jam.setValue(wkt);
        
    }//GEN-LAST:event_tampilJadwalMouseClicked

    private void matkulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matkulMouseClicked
        // TODO add your handling code here:
        matkul.setText("");
    }//GEN-LAST:event_matkulMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    
    private void tampilkanJadwal(){
        DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("No");
        tb1.addColumn("ID");
        tb1.addColumn("Mata Kuliah");
        tb1.addColumn("SKS");
        tb1.addColumn("Hari");
        tb1.addColumn("Jam");
        
        try {
            
            int counter = 1; 
//          1.  Query
            String query = "SELECT * FROM tb_jadwal";
            
//          2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();
            
//          3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
//          4.  Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
//          5. Looping  
            while (r.next()) {
                tb1.addRow(new Object[]{
                    counter++,r.getString(1),r.getString(2),r.getString(3), r.getString(4), r.getString(5)
                });
            }
            tampilJadwal.setModel(tb1);
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan saat menambahkan data ke tabel: " + e.getMessage());
        }
    }
    
    public void formatWaktu(){
        try{
            MaskFormatter timeFormatter = new MaskFormatter("##:##:##");
            timeFormatter.setPlaceholderCharacter('_');
        }catch(ParseException e){
            e.printStackTrace();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> hari;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jam;
    private javax.swing.JTextField matkul;
    private javax.swing.JTextField sks;
    private javax.swing.JTable tampilJadwal;
    // End of variables declaration//GEN-END:variables
}
