/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tubesrevisi;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.beans.PropertyVetoException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernm = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        logBut = new javax.swing.JButton();
        dafbut = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tidak Punya Akun?");

        logBut.setBackground(new java.awt.Color(0, 0, 0, 80));
        logBut.setForeground(new java.awt.Color(255, 255, 255));
        logBut.setText("Masuk");
        logBut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logButMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logButMouseExited(evt);
            }
        });
        logBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logButActionPerformed(evt);
            }
        });

        dafbut.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        dafbut.setForeground(new java.awt.Color(255, 255, 255));
        dafbut.setText("Daftar");
        dafbut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dafbutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dafbutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dafbutMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pass)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(usernm, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(dafbut)
                .addGap(136, 136, 136))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addComponent(logBut, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(usernm, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pass, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(logBut)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dafbut)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 310, 280));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tubesrevisi/empty-blackboard.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 1070, 580));

        setSize(new java.awt.Dimension(1037, 540));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logButActionPerformed
         // TODO add your handling code here:
         try{
            String username   = usernm.getText();
            String password    = pass.getText();
            
            //Query database
            String sql = "SELECT * FROM tb_user WHERE username = '" + username + "' AND password = '" + password + "'";
            Connection Vconnect = (Connection)koneksiDB.configDB();
            Statement s = Vconnect.createStatement();
            ResultSet r = s.executeQuery(sql);
            
            if(r.next()){
                JOptionPane.showMessageDialog(null, "berhasil login");
                Dashboard HalUtama = new Dashboard();
                HalUtama.setVisible(true);
                this.setVisible(false);
            }else{
                JOptionPane.showMessageDialog(null, "Username atau Password Salah");
            }
    }
        catch (Exception c){
            JOptionPane.showMessageDialog(this, c.getMessage());
            }
    }//GEN-LAST:event_logButActionPerformed

    private void dafbutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dafbutMouseClicked
        // TODO add your handling code here:
        daftar HalDaftar = new daftar();
                HalDaftar.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_dafbutMouseClicked

    private void logButMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButMouseEntered
        // TODO add your handling code here:
        logBut.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                // Animasi saat kursor masuk ke dalam tombol
                logBut.setBackground(new Color(0, 0, 0, 80));  // Mengatur latar belakang tombol menjadi transparan
                logBut.setForeground(Color.WHITE);  // Mengubah warna teks tombol menjadi hitam
                logBut.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  // Mengubah ikon kursor menjadi tangan
            }
        });
    }//GEN-LAST:event_logButMouseEntered

    private void logButMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logButMouseExited
        // TODO add your handling code here:
         logBut.addMouseListener(new MouseAdapter() {
         public void mouseExited(MouseEvent e) {
                // Animasi saat kursor keluar dari tombol
                logBut.setBackground(new Color(0, 0, 0, 80));  // Menghapus latar belakang kustom (transparan)
                logBut.setForeground(Color.WHITE);  // Mengubah warna teks tombol menjadi hitam
                logBut.setCursor(Cursor.getDefaultCursor());  // Mengembalikan ikon kursor ke bentuk aslinya
            }
        });
    }//GEN-LAST:event_logButMouseExited

    private void dafbutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dafbutMouseEntered
        // TODO add your handling code here:
        dafbut.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                dafbut.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));  // Mengubah ikon kursor menjadi tangan
            }
        });
    }//GEN-LAST:event_dafbutMouseEntered

    private void dafbutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dafbutMouseExited
        // TODO add your handling code here:
        dafbut.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) {
                dafbut.setCursor(Cursor.getDefaultCursor());  // Mengubah ikon kursor menjadi tangan
            }
        });
    }//GEN-LAST:event_dafbutMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dafbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton logBut;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField usernm;
    // End of variables declaration//GEN-END:variables
}
