/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package tubesrevisi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class tugas extends javax.swing.JInternalFrame {

    /**
     * Creates new form tugas
     */
    public tugas() {
        initComponents();
        tampilkanTugas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tampilTugas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        descArea = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        tanggal = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(697, 250));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Daftar Tugas");

        jLabel2.setText("Deskripsi Tugas");

        jLabel3.setText("Kategori");

        jLabel4.setText("Tenggat");

        tampilTugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "No", "ID", "Deskripsi", "Kategori", "Tenggat"
            }
        ));
        tampilTugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilTugasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tampilTugas);

        descArea.setColumns(20);
        descArea.setRows(5);
        jScrollPane2.setViewportView(descArea);

        jButton1.setText("Tambah");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ubah");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hapus");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel5.setText("ID");

        id.setEditable(false);
        id.setForeground(new java.awt.Color(102, 102, 102));
        id.setText("Tidak Diisi");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2)
                                .addGap(12, 12, 12)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cat, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                                    .addComponent(tanggal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(73, 73, 73)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton1))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            tanggal.equals("");
            Objects.requireNonNull(tanggal, "Tanggal tidak boleh null");
        }catch (NullPointerException e) {
            System.out.println("NullPointerException terjadi: " + e.getMessage());
        }
   
        if(descArea.equals("") && cat.equals("") && tanggal.equals("")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Lengkap Terlebih Dahulu");
        }else{
        String desc = descArea.getText();
        String kategori = cat.getText();
        Date tenggat = new Date();
        tenggat = tanggal.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyMMdd");
        String dateString = sdf.format(tenggat);
        
        
        
        String sql = "INSERT INTO tb_tugas (descTugas, kategori, tenggat) VALUES (?, ?, ?)";
            String value1 = desc;
            String value2 = kategori;
            String value3 = dateString;
            
       try(Connection Vconn = (Connection)koneksiDB.configDB();
                PreparedStatement pstmt = Vconn.prepareStatement(sql)){
                
                //java.sql.Date sqlDate = new java.sql.Date(tenggat.getTime());
                pstmt.setString(1, value1);
                pstmt.setString(2, value2);
                pstmt.setString(3,value3);
                pstmt.executeUpdate();
               
                
                JOptionPane.showMessageDialog(null, "Berhasil Menambahkan");
                descArea.setText("");
                cat.setText("");
                
                System.out.println("Data berhasil ditambahkan ke tabel.");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal Menambahkan");
                System.out.println("Terjadi kesalahan saat menambahkan data ke tabel: " + e.getMessage());
            }
            tampilkanTugas();
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        String input = id.getText();
        int option = JOptionPane.showConfirmDialog(null,  "Anda yakin Ingin Keluar Menghapus Tugas");
        if(option == 0){
            try {

   //       1.  Query
            String query = "DELETE FROM tb_tugas WHERE id = "+ input +";";
 
   //       2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();

   //       3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();

   //       4.  Eksekusi Query
            s.executeUpdate(query);

           } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "gagal hapus");
             System.out.println("Terjadi kesalahan saat menghapus data: " + e.getMessage());
           }
            descArea.setText("");
            cat.setText("");
            tanggal.setDateFormatString("");
            tampilkanTugas();
        }else{
            JOptionPane.showMessageDialog(null, "Hapus Tidak Valid");
            JOptionPane.getRootFrame().dispose();
        }
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(descArea.equals("") && cat.equals("") && tanggal.equals("Pilih Hari")){
            JOptionPane.showMessageDialog(null, "Isi Data Dengan Lengkap Terlebih Dahulu");
        }else{
            String ID = id.getText();
            String desc = descArea.getText();
            String kategori = cat.getText();
            Date tenggat = new Date();
            tenggat = tanggal.getDate();
            SimpleDateFormat sdf = new SimpleDateFormat("yyMMdd");
            String dateString = sdf.format(tenggat);
            String tgl = dateString;
            //Date tgl = tanggal.getDate();
           // String tanggal = Date.parse(tgl);
            try {

       //       1.  Query
                 String query = "UPDATE tb_tugas SET descTugas = '"+desc+"', kategori = '"+kategori+"', tenggat = '"+tgl+"' WHERE id = '"+ID+"';";

       //       2.  Fungsi koneksi
                java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();

       //       3.  Kirim Paramter fungsi Java ke SQL
                java.sql.Statement s = Vconn.createStatement();

       //       4.  Eksekusi Query
                s.executeUpdate(query);

                JOptionPane.showMessageDialog(null, "Berhasil Ubah");
               } catch (Exception e) {
                 JOptionPane.showMessageDialog(null, "Gagal Ubah");
                 System.out.println("Terjadi kesalahan saat mengubah data: " + e.getMessage());
               }
            tampilkanTugas();
        }
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tampilTugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilTugasMouseClicked
        // TODO add your handling code here:
         int baris = tampilTugas.rowAtPoint(evt.getPoint());
        
        String ID = tampilTugas.getValueAt(baris, 1).toString();
        id.setText(ID);
        
        String desc = tampilTugas.getValueAt(baris, 2).toString();
        descArea.setText(desc);
        
        String kat = tampilTugas.getValueAt(baris, 3).toString();
        cat.setText(kat);
        
        String tgl = tampilTugas.getValueAt(baris, 4).toString();
        DateFormat dt = new SimpleDateFormat("yyy-MM-dd");
        Date date = null;
        try {
            date = dt.parse(tgl);
        } catch (ParseException ex) {
            Logger.getLogger(tugas.class.getName()).log(Level.SEVERE, null, ex);
        }
        tanggal.setDate(date);
        
    }//GEN-LAST:event_tampilTugasMouseClicked

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed
 private void tampilkanTugas(){
        DefaultTableModel tb1 = new DefaultTableModel();
        tb1.addColumn("No");
        tb1.addColumn("ID");
        tb1.addColumn("Deskripsi");
        tb1.addColumn("Kategori");
        tb1.addColumn("Tenggat");
        
        try {
            int counter = 1; 
//          1.  Query
            String query = "SELECT * FROM tb_tugas";
            
//          2.  Fungsi koneksi
            java.sql.Connection Vconn = (java.sql.Connection)koneksiDB.configDB();
            
//          3.  Kirim Paramter fungsi Java ke SQL
            java.sql.Statement s = Vconn.createStatement();
            
//          4.  Eksekusi Query
            java.sql.ResultSet r = s.executeQuery(query);
            
//          5. Looping  
            while (r.next()) {
                tb1.addRow(new Object[]{
                    counter++,r.getString(1),r.getString(2),r.getString(3), r.getString(4)
                });
            }
            tampilTugas.setModel(tb1);
        } catch (Exception e) {
            System.out.println("Terjadi kesalahan saat menambahkan data ke tabel: " + e.getMessage());
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cat;
    private javax.swing.JTextArea descArea;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tampilTugas;
    private com.toedter.calendar.JDateChooser tanggal;
    // End of variables declaration//GEN-END:variables
}
